#!/usr/bin/env bash
if [[ $# -eq 1 ]]
then
	awk -v "DEL=$1" '{ if (NR == 1) { printf("%s", $0); } else { printf("%s%s", DEL, $0); } } END { if (NR > 0) { printf("\n"); } }'
else
	echo "Usage: $0 <delimiter-char>" 2>&1
	exit 1
fi
