#!/usr/bin/env bash
if [[ $# -eq 2 ]]
then
	input=$1
	duration=$2
	shift 2
else
	echo "Usage: $0 <input> <duration>"
	exit 1
fi
dir="$(dirname "$input")/cutfirst"
output="$dir/$(basename "$input")"
mkdir -p "$dir"
if ffmpeg -ss "$duration" -i "$input" "$output"
then
	echo "[ OK ] Input: $input Output: $output" >> log.txt
else
	echo "[ FAIL ] Input: $input" >> log.txt
fi
