#!/usr/bin/env bash
if [[ $# -eq 2 ]]
then
	input=$1
	duration=$2
	shift 2
else
	echo "Usage: $0 <input> <duration>"
	exit 1
fi
dir="$(dirname "$input")/cutlast"
output="$dir/$(basename "$input")"
mkdir -p "$dir"
total=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$input" 2>&1)
final=$(echo "($total - $duration)" | bc -l)
if ffmpeg -i "$input" -t "$final" -c copy "$output"
then
	echo "[ OK ] Input: $input Output: $output" >> log.txt
else
	echo "[ FAIL ] Input: $input" >> log.txt
fi
