#!/usr/bin/env bash
if [[ $# -eq 2 ]]
then
	set -e
	frame=$(ffmpeg -i "$1" 2>&1 | \
		grep Duration | \
		awk '{print $2}' | \
		tr -d , | \
		awk -F ':' '{print ($3+$2*60+$1*3600)/2}')
	ffmpeg -i "$1" -vcodec mjpeg -vframes 1 -an -f rawvideo -ss "$frame" "$2"
else
	echo "Usage: $0 <video-input> <image-output>"
fi
