#!/usr/bin/env bash
if [[ $# -eq 2 ]]
then
	input=$1
	rotate=$2
	shift 2
else
	echo "Usage: $0 <input> <rotate>"
	echo ""
	echo "Possible values for <rotate>:"
    echo "0 - Rotate by 90 degrees counter-clockwise and flip vertically. This is the default."
    echo "1 - Rotate by 90 degrees clockwise."
    echo "2 - Rotate by 90 degrees counter-clockwise."
    echo "3 - Rotate by 90 degrees clockwise and flip vertically."
	exit 1
fi
dir="$(dirname "$input")/rotated"
output="$dir/$(basename "$input")"
mkdir -p "$dir"
if ffmpeg -i "$input" -vf "transpose=$rotate" "$output"
then
	echo "[ OK ] Input: $input Output: $output" >> log.txt
else
	echo "[ FAIL ] Input: $input" >> log.txt
fi
