#!/usr/bin/env bash
awk 'NF >= 1 {
	t = $1
	i = 0

	while (t != 0)
	{
		v[i++] = t % 60;
		t = int(t / 60);
	}

	if (i == 0)
	{
		print "00:00"
	}
	else if (i == 1)
	{
		printf "00:%02d\n", v[0]
	}
	else
	{
		for (j = i - 1; j > 0; --j)
		{
			printf "%02d:", v[j]
		}

		printf "%02d\n", v[0]
	}
}'
