#!/usr/bin/env bash
# Usage: cat files.txt | totalduration
# Returns total number of minutes

total=0
while read file
do
	dur=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$file")
	total=$(echo "($total + $dur)" | bc -l)
done
echo "($total / 60)" | bc -l
