#!/usr/bin/env bash
if [[ $# -eq 3 ]]
then
	t=`echo "$3" "$2" | timediff`
	name="${1%.*}_${2//:/-}_${3//:/-}.${1##*.}"
	ffmpeg -ss "$2" -i "$1" -t "$t" -c copy "$name"
else
	echo "Usage: $0 <input-file> <start-ts> <final-ts>"
fi
