#!/usr/bin/env bash
set -e
if [[ $# -ge 2 ]]
then
    input=$1
    output=$2
    shift 2
else
	echo "Usage: $0 <input> <output>"
    exit 1
fi
ffmpeg -i "$input" \
  -vf 'split[original][copy];[copy]scale=ih*16/9:-1,crop=h=iw*9/16,gblur=sigma=20[blurred];[blurred][original]overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2' \
  "$output"
